### ISSUE TITLE
Winget is not up to date

### ISSUE THREAD

**Issue by Kaarel** [carapace-sh/carapace#1049]
### Current Behavior

`winget search carapace`
```
Name     Id               Version Source
-----------------------------------------
Carapace rsteube.Carapace 1.0.7   winget
```

### Expected Behavior

Should match the actual current version on GH. (as of reporting `1.4.0`)

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

## Polar

<a href="https://polar.sh/carapace-sh/carapace/issues/1049">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace/issues/1049/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace/issues/1049/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
This is understandably a bit misleading:
- [carapace-sh/carapace](https://github.com/carapace-sh/carapace) is the library
- [carapace-sh/carapace-bin](https://github.com/carapace-sh/carapace-bin) is the **bin**ary providing the `carapace` command (and winget package)

To make things worse: both are referred to with `carapace` as the whole thing has grown to an ecosystem of different projects.
So depending on context the library or binary can be meant.
