### ISSUE TITLE
Completions Contain Trailing space

### ISSUE THREAD

**Issue by Karuption** [carapace-sh/carapace#1051]
### Current Behavior

When doing a completion, there is a trailing space.

### Expected Behavior

Native completions do not include a space in powershell, even on flag completions. I would expect carapace to be idiomatic with these.

### Steps To Reproduce

1. In windows 10, using Terminal
2. My $PROFILE:
``` pwsh
   Import-Module PSFzf
   Set-PSReadLineKeyHandler -Key Tab -ScriptBlock { Invoke-FzfTabCompletion }

    $env:CARAPACE_BRIDGES = 'zsh,fish,bash,inshellisense' # optional
    carapace _carapace | Out-String | Invoke-Expression
  ```
3. Type `gh a <TAB>`
4. Select Alias from the FZF window
5. Auto completion of `gh "alias "`

### Version

1.0.7

### OS

- [ ] Darwin
- [ ] Linux
- [ ] Termux
- [X] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [X] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

I can see that the json generated by `carapace gh powershell a ` has a trailing space in its `CompletionText`. Since there is a char in the string that needs to be escaped, FZF puts quotes around it for a literal. 

The trailing space is visible by doing:
``` pwsh 
carapace.exe gh powershell a  | ConvertFrom-Json | Select-Object -First 1 -ExpandProperty CompletionText  | Select-String -Pattern .*
```

This functionality seems like it is intentional, but I am not able to find exactly where in the code (or spec) that this is happening. A configuration option to disable or set the trailing options would be amazing.

## Polar

<a href="https://polar.sh/carapace-sh/carapace/issues/1051">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/carapace-sh/carapace/issues/1051/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/carapace-sh/carapace/issues/1051/pledge.svg">
</picture>
</a>

**Comment by rsteube** [comment]
Yes, this is an intentional feature for fluent completion and one of the things powershell doesn't do well.
I can understand though how the inconsistency can be disrupting and adding this is fairly easy.

**Comment by Karuption** [comment]
Thank you! Looking forward to the next release.
